// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ApeChainPoWNFT$Type } from "./ApeChainPoWNFT";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ApeChainPoWNFT"]: ApeChainPoWNFT$Type;
    ["contracts/ApeChainPoWNFT.sol:ApeChainPoWNFT"]: ApeChainPoWNFT$Type;
  }

  interface ContractTypesMap {
    ["ApeChainPoWNFT"]: GetContractReturnType<ApeChainPoWNFT$Type["abi"]>;
    ["contracts/ApeChainPoWNFT.sol:ApeChainPoWNFT"]: GetContractReturnType<ApeChainPoWNFT$Type["abi"]>;
  }
}
